CREATE DATABASE TestSQLServer

CREATE TABLE students(
ID INT NOT NULL IDENTITY PRIMARY KEY,
NAME VARCHAR(50),
EMAIL VARCHAR(50),
GRADE VARCHAR(2)

);

INSERT INTO students VALUES ('Pablo', 'Pablo@gmail.com','A');

SELECT * FROM students